package prueba.soft.Selenium_Cucumber.test;

//Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;

import static org.junit.jupiter.api.Assertions.*;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.boot.test.context.SpringBootTest;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;


@SpringBootTest
public class SeleniumTest {
	private WebDriver driver;
    private static final String TIPO_DRIVER = "webdriver.edge.driver";
    private static final String PATH_DRIVER = "./src/main/resources/webDriver/msedgedriver.exe";

	//private Map<String, Object> vars;
	JavascriptExecutor js;
	
	@BeforeEach
	public void setUp() {
	 System.setProperty(TIPO_DRIVER, PATH_DRIVER);
	 driver = new EdgeDriver();
	 js = (JavascriptExecutor) driver;
	 //vars = new HashMap<String, Object>();
	}
	
	@AfterEach
	public void tearDown() {
	 driver.quit();
	}
	
	@Test
	public void loginExitoso() {
		 // Test name: Login Exitoso
		 // Step # | name | target | value
		 // 1 | open | / | 
		 driver.get("https://www.saucedemo.com/");
		 // 2 | setWindowSize | 1552x832 | 
		 driver.manage().window().setSize(new Dimension(1552, 832));
		 // 3 | click | css=*[data-test="username"] | 
		 driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
		 // 4 | type | css=*[data-test="username"] | standard_user
		 // Ingreso el usuario correcto
		 driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
		 // 5 | click | css=*[data-test="password"] | 
		 driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
		 // 6 | click | css=*[data-test="password"] | 
		 driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
		 // 7 | type | css=*[data-test="password"] | secret_sauce
		 // Ingreso la contrase correcta
		 driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
		 // 8 | click | css=*[data-test="login-button"] | 
		 // Click en login y me permite ingresar
		 driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();

	}
	
	@Test
	  public void realizarCompra() {
	    driver.get("https://www.saucedemo.com/");
	    driver.manage().window().setSize(new Dimension(1552, 832));
	    
	    /*Start - Login*/
	    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
	    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
	    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
	    /* End - Login*/
	    
	    /*Start - Agregamos productos al carro*/
	    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-fleece-jacket\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-onesie\"]")).click();
	    /*End - Agregamos productos al carro*/
	    
	    /*Start - Compra*/
	    driver.findElement(By.cssSelector("*[data-test=\"shopping-cart-link\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
	    
	    /*Ingreso de datos de la compra*/
	    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("Armando");
	    driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("Paredes");
	    driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("1234");
	    driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
	    /*End - Compra*/
	    
	    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();

	  }
	
	@Test
	  public void verificarPrecioProductos() {
	    driver.get("https://www.saucedemo.com/");
	    driver.manage().window().setSize(new Dimension(1552, 832));
	    
	    /*Start - Login*/
	    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
	    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
	    driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
	    /* End - Login*/
	    
	    /*Start - Validacion de precios*/
	    driver.findElement(By.cssSelector("#item_2_title_link > .inventory_item_name")).click();
	    assertThat(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-price\"]")).getText(), is("$7.99"));
	    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
	    driver.findElement(By.cssSelector("*[data-test=\"inventory-item-name\"]")).click();
	    assertThat(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-price\"]")).getText(), is("$29.99"));
	    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
	    driver.findElement(By.cssSelector("#item_0_title_link > .inventory_item_name")).click();
	    assertThat(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-price\"]")).getText(), is("$9.99"));
	    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
	    driver.findElement(By.cssSelector("#item_1_title_link > .inventory_item_name")).click();
	    assertThat(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-price\"]")).getText(), is("$15.99"));
	    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
	    driver.findElement(By.cssSelector("#item_5_title_link > .inventory_item_name")).click();
	    assertThat(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-price\"]")).getText(), is("$49.99"));
	    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
	    driver.findElement(By.cssSelector("#item_3_title_link > .inventory_item_name")).click();
	    assertThat(driver.findElement(By.cssSelector("*[data-test=\"inventory-item-price\"]")).getText(), is("$15.99"));
	    /*End - Validacion de precios*/
	    
	    driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
	    
	  }
}
