package prueba.soft.Selenium_Cucumber.test;

//Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;

import static org.junit.jupiter.api.Assertions.*;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.boot.test.context.SpringBootTest;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@SpringBootTest
public class SeleniumTest {
	private WebDriver driver;
    private static final String TIPO_DRIVER = "webdriver.edge.driver";
    private static final String PATH_DRIVER = "./src/main/resources/webDriver/msedgedriver.exe";

	//private Map<String, Object> vars;
	JavascriptExecutor js;
	
	@BeforeEach
	public void setUp() {
	 System.setProperty(TIPO_DRIVER, PATH_DRIVER);
	 driver = new EdgeDriver();
	 js = (JavascriptExecutor) driver;
	 //vars = new HashMap<String, Object>();
	}
	
	@AfterEach
	public void tearDown() {
	 driver.quit();
	}
	
	@Test
	public void loginExitoso() {
		 // Test name: Login Exitoso
		 // Step # | name | target | value
		 // 1 | open | / | 
		 driver.get("https://www.saucedemo.com/");
		 // 2 | setWindowSize | 1552x832 | 
		 driver.manage().window().setSize(new Dimension(1552, 832));
		 // 3 | click | css=*[data-test="username"] | 
		 driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
		 // 4 | type | css=*[data-test="username"] | standard_user
		 // Ingreso el usuario correcto
		 driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
		 // 5 | click | css=*[data-test="password"] | 
		 driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
		 // 6 | click | css=*[data-test="password"] | 
		 driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
		 // 7 | type | css=*[data-test="password"] | secret_sauce
		 // Ingreso la contrase correcta
		 driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
		 // 8 | click | css=*[data-test="login-button"] | 
		 // Click en login y me permite ingresar
		 driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();

	}
}
